---
- user_attributes:
    admin:
      groups:
        - EnforceMFA
        - AdminAccess
      aws_tags:
        "user-role": operations
    readonly:
      groups:
        - EnforceMFA
        - ReadonlyAccess
      aws_tags:
        "user-role": readonly
    ithc:
      groups:
        - EnforceMFA
        - ItchReadOnlyAccess
      aws_tags:
        "user-role": ithc

- users_enabled:
    - name: ben_pirt
      type: admin
    - name: emad_karamad
      type: admin
    - name: joe_folkard
      type: admin
    - name: ian_king
      type: admin
    - name: richard_cane
      type: admin
    - name: richard_race
      type: admin
    - name: tausif_patel
      type: admin
    - name: irene_grande
      type: admin
    - name: tom_watkins
      type: admin
    - name: emma_lanigan
      type: admin
    - name: lili_berenyi
      type: admin
    - name: ithc_user
      type: ithc

- users_removed:
    - name: wenting_wang
