---
- user_attributes:
    admin:
      groups:
        - EnforceMFA
        - AdminAccess
        - AWSSupportAccess
      aws_tags:
        "user-role": operations
    readonly:
      groups:
        - EnforceMFA
        - ReadOnlyAccess
      aws_tags:
        "user-role": readonly
    ithc:
      groups:
        - EnforceMFA
        - IthcReadOnlyAccess
      aws_tags:
        "user-role": ithc

- users_enabled:
    - name: ben_pirt
      type: admin
    - name: emad_karamad
      type: admin
    - name: joe_folkard
      type: admin
    - name: richard_cane
      type: admin
    - name: richard_race
      type: admin
    - name: tausif_patel
      type: admin
    - name: irene_grande
      type: admin
    - name: tom_watkins
      type: admin
    - name: kate_reidy
      type: admin
    - name: wren_hawthorne
      type: admin

- users_removed:
    - name: lili_berenyi
